application: gaejstable
version: 0-1a
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- appstats: on
- deferred: on
- datastore_admin: on
- remote_api: on

inbound_services:
- warmup
- channel_presence

error_handlers:
- file: templates/error_handlers/default_error.html

- error_code: over_quota
  file: templates/error_handlers/over_quota.html

- error_code: dos_api_denial
  file: templates/error_handlers/dos_api_denial.html

- error_code: timeout
  file: templates/error_handlers/timeout.html

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/vnd.microsoft.icon

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  expiration: 7d

- url: /static
  static_dir: static
  expiration: 7d

- url: /_ah/queue/deferred
  script: main.app
  login: admin

- url: /tasks/.+
  script: main.app
  login: admin

- url: /.*
  script: main.app

skip_files:
- ^(.*/)?.*\.my$
- ^(.*/)?app\.ya?ml$
- ^(.*/)?index\.ya?ml$
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.so$
- ^(.*/)?.*/.bak$

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: setuptools
  version: latest
